In [2]:
import pandas as pd

In [3]:
all_waybill = pd.read_csv('data/all_waybill_info_meituan_0322.csv')
all_waybill.drop('Unnamed: 0', axis=1, inplace=True)

In [4]:
print(len(all_waybill))
print(all_waybill.columns)

654343
Index(['dt', 'order_id', 'waybill_id', 'courier_id', 'da_id',
       'is_courier_grabbed', 'is_weekend', 'estimate_arrived_time',
       'is_prebook', 'poi_id', 'sender_lng', 'sender_lat', 'recipient_lng',
       'recipient_lat', 'grab_lng', 'grab_lat', 'dispatch_time', 'grab_time',
       'fetch_time', 'arrive_time', 'estimate_meal_prepare_time',
       'order_push_time', 'platform_order_time'],
      dtype='object')

In [5]:
all_waybill.head(15)

,dt,order_id,waybill_id,courier_id,da_id,is_courier_grabbed,is_weekend,estimate_arrived_time,is_prebook,poi_id,...,recipient_lat,grab_lng,grab_lat,dispatch_time,grab_time,fetch_time,arrive_time,estimate_meal_prepare_time,order_push_time,platform_order_time
0,20221017,0,0,0,0,0,1,1665937978,0,0,...,45852786,0,0,1665936258,0,0,0,1665936779,1665936000,1665935996
1,20221017,1,1,1,1,1,1,1665937864,0,1,...,45898250,174530062,45906005,1665936734,1665936737,1665937344,1665937798,1665936845,1665936006,1665935995
2,20221017,2,2,2,2,1,0,1665939504,0,2,...,45891243,174548244,45870923,1665937484,1665937501,1665938346,1665939384,1665938007,1665937107,1665937097
3,20221017,3,3,3,0,1,0,1665939432,0,3,...,45886787,174560199,45867948,1665937394,1665937397,1665937830,1665939822,1665937634,1665937369,1665937028
4,20221017,4,4,4,0,1,0,1665938894,0,3,...,45867411,174554896,45865167,1665937394,1665937413,1665937710,1665938262,1665937694,1665937373,1665937092
5,20221017,5,5,5,3,1,0,1665940500,0,4,...,45921310,174526338,45912309,1665938727,1665938741,1665940061,1665940496,1665939225,1665938403,1665938399
6,20221017,6,6,6,2,1,0,1665943672,0,5,...,45878207,174561783,45868495,1665941954,1665941993,1665942156,1665942859,1665942172,1665941872,1665941566
7,20221017,7,7,7,2,1,0,1665944770,0,5,...,45884833,174557275,45876124,1665942674,1665942684,1665943165,1665944308,1665942970,1665942670,1665942362
8,20221017,8,8,8,4,0,0,1665970200,1,6,...,45835245,0,0,1665966555,0,0,0,1665945737,1665944915,1665944899
9,20221017,9,9,9,5,1,0,1665948557,0,7,...,45888878,174555549,45896141,1665946604,1665946623,1665946951,1665947591,1665947117,1665946517,1665946511
10,20221017,10,10,10,0,1,0,1665949928,0,8,...,45853516,174572714,45860220,1665948254,1665948263,1665948809,1665949058,1665949091,1665948132,1665948120
11,20221017,11,11,11,0,1,0,1665957504,0,9,...,45867795,174582161,45867402,1665955724,1665955749,1665956326,1665956731,1665956305,1665955705,1665955685
12,20221017,12,12,12,6,1,0,1665960892,0,10,...,46044014,174944483,46052374,1665959097,1665959106,1665960550,1665960788,1665959933,1665959093,1665959082
13,20221017,13,13,13,7,1,0,1665978000,1,11,...,45859803,174552394,45851018,1665975406,1665975418,1665976093,1665977540,1665959867,1665959268,1665936351
14,20221017,14,14,14,4,1,0,1665961500,0,12,...,45853337,174593374,45862036,1665959654,1665959670,1665960708,1665961359,1665959523,1665959523,1665959519

In [6]:
# all_waybill[all_waybill['waybill_id'] == all_waybill['order_id']]
# # Get rows 10000 to 10010
# print(all_waybill.iloc[2693:2713])

# Data Summary
Order_id: Numerical id for a person's order \
Waybill_id: Numberical order for a waybill. One order_id can have multiple waybill_id if the first is rejected and then put back into the system. \
dt: Date and time of order creation \
courier_id: Numerical id for a courier \
da_id: Area id of a business district \
poi_id: merchant id \
order_push_time: Unix time when order enters the dispatch system for assignment \
grab_lat/lng: Long/Lat of courier when the order is assigned to them \
is_courier_gradded: Boolean, whether waybill is accepted or rejected \
grab,fetch,arrive_time: Sequence of when courier accepts, collects, then delivers the order \

### Intuitive Stuff:
is_weekend: Boolean, weekend or not \
estimate_arrived_time: System promised deliver time \
is_prebook: Pre-booked in the system or not \
sender_lat/lng: Lat/Long of the pickup point (restaurant) \
recipient_lat/lng: Lat/Long of the dropoff (customer home/business/wherever) \
dispatch_time: Waybill is assigned to courier (can be refused) \
estimate_meal_prepare_time: When meal is ready to get \
platform_order_time: Order sent by customer 

**None of the data is able to be combined/aggregated into single columns**

In [7]:
# If numerical, print out the range of values in each column
for col in all_waybill.columns:
    if all_waybill[col].dtype == 'int64' and all_waybill[col].max() != 1:
        print(col, all_waybill[col].min(), all_waybill[col].max())

dt 20221017 20221024
order_id 0 568545
waybill_id 0 654342
courier_id 0 4954
da_id 0 22
estimate_arrived_time 1665937540 1666641420
poi_id 0 4961
sender_lng 174481806 174988918
sender_lat 45755268 46067416
recipient_lng 174387310 174994756
recipient_lat 45729124 46072996
grab_lng 0 174999535
grab_lat 0 46079853
dispatch_time 0 1666627966
grab_time 0 1666628609
fetch_time 0 1666629477
arrive_time 0 1666629978
estimate_meal_prepare_time 0 1666628312
order_push_time 1665544699 1666627199
platform_order_time 1665494980 1666627188

In [8]:
import math
# Calculate distances using Haversine Formula
def calc_distance(lat1, long1, lat2, long2):
    R = 6356.752 # Polar Radius of the Earth in km (https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html)
    # Convert to radians
    lat_rad_1 = math.radians(lat1)
    long_rad_1 = math.radians(long1)
    lat_rad_2 = math.radians(lat2)
    long_rad_2 = math.radians(long2)
    
    delta_1 = lat_rad_2 - lat_rad_1
    delta_2 = long_rad_2 - long_rad_1
    
    inside = math.sin(delta_1/2)**2 + math.cos(lat_rad_1) * math.cos(lat_rad_2) * math.sin(delta_2/2)**2
    dist = 2 * R * math.asin(math.sqrt(inside))
    
    return dist

In [9]:
# Make a new table with the first 10 rows of all_waybill
testing = all_waybill.head(10).copy()
testing

,dt,order_id,waybill_id,courier_id,da_id,is_courier_grabbed,is_weekend,estimate_arrived_time,is_prebook,poi_id,...,recipient_lat,grab_lng,grab_lat,dispatch_time,grab_time,fetch_time,arrive_time,estimate_meal_prepare_time,order_push_time,platform_order_time
0,20221017,0,0,0,0,0,1,1665937978,0,0,...,45852786,0,0,1665936258,0,0,0,1665936779,1665936000,1665935996
1,20221017,1,1,1,1,1,1,1665937864,0,1,...,45898250,174530062,45906005,1665936734,1665936737,1665937344,1665937798,1665936845,1665936006,1665935995
2,20221017,2,2,2,2,1,0,1665939504,0,2,...,45891243,174548244,45870923,1665937484,1665937501,1665938346,1665939384,1665938007,1665937107,1665937097
3,20221017,3,3,3,0,1,0,1665939432,0,3,...,45886787,174560199,45867948,1665937394,1665937397,1665937830,1665939822,1665937634,1665937369,1665937028
4,20221017,4,4,4,0,1,0,1665938894,0,3,...,45867411,174554896,45865167,1665937394,1665937413,1665937710,1665938262,1665937694,1665937373,1665937092
5,20221017,5,5,5,3,1,0,1665940500,0,4,...,45921310,174526338,45912309,1665938727,1665938741,1665940061,1665940496,1665939225,1665938403,1665938399
6,20221017,6,6,6,2,1,0,1665943672,0,5,...,45878207,174561783,45868495,1665941954,1665941993,1665942156,1665942859,1665942172,1665941872,1665941566
7,20221017,7,7,7,2,1,0,1665944770,0,5,...,45884833,174557275,45876124,1665942674,1665942684,1665943165,1665944308,1665942970,1665942670,1665942362
8,20221017,8,8,8,4,0,0,1665970200,1,6,...,45835245,0,0,1665966555,0,0,0,1665945737,1665944915,1665944899
9,20221017,9,9,9,5,1,0,1665948557,0,7,...,45888878,174555549,45896141,1665946604,1665946623,1665946951,1665947591,1665947117,1665946517,1665946511

In [16]:
testing['send_recip_distance'] = testing.apply(lambda x: round(calc_distance(x['sender_lat'], x['sender_lng'], x['recipient_lat'], x['recipient_lng']), 5),axis=1)
testing

,dt,order_id,waybill_id,courier_id,da_id,is_courier_grabbed,is_weekend,estimate_arrived_time,is_prebook,poi_id,...,grab_lng,grab_lat,dispatch_time,grab_time,fetch_time,arrive_time,estimate_meal_prepare_time,order_push_time,platform_order_time,send_recip_distance
0,20221017,0,0,0,0,0,1,1665937978,0,0,...,0,0,1665936258,0,0,0,1665936779,1665936000,1665935996,17406.42950
1,20221017,1,1,1,1,1,1,1665937864,0,1,...,174530062,45906005,1665936734,1665936737,1665937344,1665937798,1665936845,1665936006,1665935995,4437.85009
2,20221017,2,2,2,2,1,0,1665939504,0,2,...,174548244,45870923,1665937484,1665937501,1665938346,1665939384,1665938007,1665937107,1665937097,5885.90874
3,20221017,3,3,3,0,1,0,1665939432,0,3,...,174560199,45867948,1665937394,1665937397,1665937830,1665939822,1665937634,1665937369,1665937028,5573.60079
4,20221017,4,4,4,0,1,0,1665938894,0,3,...,174554896,45865167,1665937394,1665937413,1665937710,1665938262,1665937694,1665937373,1665937092,11960.91776
5,20221017,5,5,5,3,1,0,1665940500,0,4,...,174526338,45912309,1665938727,1665938741,1665940061,1665940496,1665939225,1665938403,1665938399,8573.72404
6,20221017,6,6,6,2,1,0,1665943672,0,5,...,174561783,45868495,1665941954,1665941993,1665942156,1665942859,1665942172,1665941872,1665941566,9514.87487
7,20221017,7,7,7,2,1,0,1665944770,0,5,...,174557275,45876124,1665942674,1665942684,1665943165,1665944308,1665942970,1665942670,1665942362,14059.09220
8,20221017,8,8,8,4,0,0,1665970200,1,6,...,0,0,1665966555,0,0,0,1665945737,1665944915,1665944899,8847.60716
9,20221017,9,9,9,5,1,0,1665948557,0,7,...,174555549,45896141,1665946604,1665946623,1665946951,1665947591,1665947117,1665946517,1665946511,2463.77354